# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b179796ab6a1d9cbf6ab1aedd1ca991b6d3275d11692da246457160f906e6e38140779dec4a195a0a178ad7af706c3e0b1d37456584e81551c8f91db0dbb569

test:
  secret_key_base: fbf270e3dbf9206ac0f47d66d6f7a42ad1c9b3e6a11820b6c80e62070b7f673064b6a2d464d5e4b9882dba157504ce0160440a93f39c64c610b291e145a3b5f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
